name: Scala CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: temurin
    - name: Compile
      run: sbt compile
    - name: show example
      run: sbt "show Compile/compile" > out.txt
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: "test"
        path: "out.txt"
