name: Scala CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Compile
      run: sbt compile
    - name: Classpath
      run: sbt --error fullClasspath > out.txt
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: "test"
        path: "out.txt"
